services:
  # Auth Service
  - type: web
    name: parkease-auth
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Auth/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_auth;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true

  # Booking Service
  - type: web
    name: parkease-booking
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Booking/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_booking;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true
      - key: ServiceUrls__SpotService
        value: https://parkease-spot.onrender.com

  # Notification Service
  - type: web
    name: parkease-notification
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Notification/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_notification;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true

  # ParkingLot Service
  - type: web
    name: parkease-parkinglot
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.ParkingLot/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_parkinglot;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true

  # Payment Service
  - type: web
    name: parkease-payment
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Payment/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_payment;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true

  # Spot Service
  - type: web
    name: parkease-spot
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Spot/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_spot;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true

  # Vehicle Service
  - type: web
    name: parkease-vehicle
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ParkEase.Vehicle/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RabbitMQ__Host
        value: shrimp.rmq.cloudamqp.com
      - key: RabbitMQ__Username
        value: uqfenpdj
      - key: RabbitMQ__Password
        value: cHciJ4wVhs-QytxK9p6i6FnqxHyAwGRY
      - key: RabbitMQ__VirtualHost
        value: uqfenpdj
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d7is8kvaqgkc73a4d3f0-a.virginia-postgres.render.com;Port=5432;Database=parkease_vehicle;Username=parkease_yfo2_user;Password=EVSwWebkrsxGPZiLjqGsnYxh8eEcFn0W;SSL Mode=Require;TrustServerCertificate=true
