using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ParkEase.Payment.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_catalog.pg_tables WHERE schemaname = 'public' AND tablename = 'payments') THEN
                        CREATE TABLE payments (
                            payment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            booking_id integer NOT NULL,
                            user_id integer NOT NULL,
                            amount double precision NOT NULL,
                            status character varying(20) NOT NULL DEFAULT 'PENDING',
                            mode character varying(20) NOT NULL,
                            razorpay_order_id text,
                            razorpay_payment_id text,
                            currency character varying(10) NOT NULL DEFAULT 'INR',
                            description text,
                            paid_at timestamp with time zone,
                            refunded_at timestamp with time zone,
                            refund_amount double precision,
                            refund_reason text,
                            created_at timestamp with time zone NOT NULL
                        );
                        
                        CREATE INDEX IX_payments_booking_id ON payments(booking_id);
                        CREATE INDEX IX_payments_razorpay_order_id ON payments(razorpay_order_id);
                        CREATE INDEX IX_payments_razorpay_payment_id ON payments(razorpay_payment_id);
                        CREATE INDEX IX_payments_status ON payments(status);
                        CREATE INDEX IX_payments_user_id ON payments(user_id);
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "payments");
        }
    }
}
